import type { getTranslations } from "next-intl/server";
import type { ObservatoryLabels } from "@/components/observatory/types";

export function labelsFromTranslations(
  t: Awaited<ReturnType<typeof getTranslations>>,
): ObservatoryLabels {
  return {
    title: t("title"),
    subtitle: t("subtitle"),
    projectTitle: t("projectTitle"),
    correctionRate: t("correctionRate"),
    correctionFormula: t("correctionFormula"),
    rework: t("rework"),
    retries: t("retries"),
    runs: t("runs"),
    autonomyScore: t("autonomyScore"),
    waitTime: t("waitTime"),
    openWaits: t("openWaits"),
    volatile: t("volatile"),
    reviewDwellExcluded: t("reviewDwellExcluded"),
    nodes: t("nodes"),
    noNodes: t("noNodes"),
    artifacts: t("artifacts"),
    noArtifacts: t("noArtifacts"),
    signals: t("signals"),
    noSignals: t("noSignals"),
    observationsOnly: t("observationsOnly"),
    filters: t("filters"),
    artifactDefId: t("artifactDefId"),
    artifactKind: t("artifactKind"),
    flow: t("flow"),
    node: t("node"),
    lookback: t("lookback"),
    apply: t("apply"),
    all: t("all"),
    days: t("days"),
    drillDown: t("drillDown"),
    latestAttempt: t("latestAttempt"),
    historicalAttempts: t("historicalAttempts"),
    gates: t("gates"),
    hitlWaits: t("hitlWaits"),
    kind: {
      gate: t("kind.gate"),
      retry: t("kind.retry"),
      rework: t("kind.rework"),
    },
    harness: {
      sectionTitle: t("harness.sectionTitle"),
      sectionSubtitle: t("harness.sectionSubtitle"),
      firingTitle: t("harness.firingTitle"),
      noFiring: t("harness.noFiring"),
      gate: t("harness.gate"),
      kind: t("harness.kind"),
      mode: t("harness.mode"),
      executions: t("harness.executions"),
      passed: t("harness.passed"),
      failed: t("harness.failed"),
      stale: t("harness.stale"),
      failRate: t("harness.failRate"),
      neverFired: t("harness.neverFired"),
      neverFiredHint: t("harness.neverFiredHint"),
      insufficientData: t("harness.insufficientData"),
      byKind: t("harness.byKind"),
      coverageTitle: t("harness.coverageTitle"),
      noCoverage: t("harness.noCoverage"),
      revisions: t("harness.revisions"),
      blocking: t("harness.blocking"),
      advisory: t("harness.advisory"),
      guides: t("harness.guides"),
      guidesWithoutSensors: t("harness.guidesWithoutSensors"),
      effectivenessTitle: t("harness.effectivenessTitle"),
      noEffectiveness: t("harness.noEffectiveness"),
      capabilitiesTitle: t("harness.capabilitiesTitle"),
      reworkAfterFail: t("harness.reworkAfterFail"),
      reworkAfterPass: t("harness.reworkAfterPass"),
      lift: t("harness.lift"),
      capability: t("harness.capability"),
      withCapability: t("harness.withCapability"),
      withoutCapability: t("harness.withoutCapability"),
      noCapabilities: t("harness.noCapabilities"),
    },
    budget: {
      title: t("budget.title"),
      subtitle: t("budget.subtitle"),
      escalations: t("budget.escalations"),
      terminations: t("budget.terminations"),
      warnNotSurfaced: t("budget.warnNotSurfaced"),
    },
  };
}
