import type { getTranslations } from "next-intl/server";
import type { ObservatoryLabels } from "@/components/observatory/types";

export function labelsFromTranslations(
  t: Awaited<ReturnType<typeof getTranslations>>,
): ObservatoryLabels {
  return {
    title: t("title"),
    subtitle: t("subtitle"),
    projectTitle: t("projectTitle"),
    correctionRate: t("correctionRate"),
    correctionFormula: t("correctionFormula"),
    rework: t("rework"),
    retries: t("retries"),
    runs: t("runs"),
    autonomyScore: t("autonomyScore"),
    waitTime: t("waitTime"),
    openWaits: t("openWaits"),
    volatile: t("volatile"),
    reviewDwellExcluded: t("reviewDwellExcluded"),
    nodes: t("nodes"),
    noNodes: t("noNodes"),
    artifacts: t("artifacts"),
    noArtifacts: t("noArtifacts"),
    signals: t("signals"),
    noSignals: t("noSignals"),
    observationsOnly: t("observationsOnly"),
    filters: t("filters"),
    artifactDefId: t("artifactDefId"),
    artifactKind: t("artifactKind"),
    flow: t("flow"),
    runKind: t("runKind"),
    flowRuns: t("flowRuns"),
    flowLedgerOnly: t("flowLedgerOnly"),
    node: t("node"),
    lookback: t("lookback"),
    apply: t("apply"),
    all: t("all"),
    days: t("days"),
    drillDown: t("drillDown"),
    latestAttempt: t("latestAttempt"),
    historicalAttempts: t("historicalAttempts"),
    gates: t("gates"),
    hitlWaits: t("hitlWaits"),
    kind: {
      gate: t("kind.gate"),
      retry: t("kind.retry"),
      rework: t("kind.rework"),
    },
    harness: {
      sectionTitle: t("harness.sectionTitle"),
      sectionSubtitle: t("harness.sectionSubtitle"),
      firingTitle: t("harness.firingTitle"),
      noFiring: t("harness.noFiring"),
      gate: t("harness.gate"),
      kind: t("harness.kind"),
      mode: t("harness.mode"),
      executions: t("harness.executions"),
      passed: t("harness.passed"),
      failed: t("harness.failed"),
      stale: t("harness.stale"),
      failRate: t("harness.failRate"),
      neverFired: t("harness.neverFired"),
      neverFiredHint: t("harness.neverFiredHint"),
      insufficientData: t("harness.insufficientData"),
      byKind: t("harness.byKind"),
      coverageTitle: t("harness.coverageTitle"),
      noCoverage: t("harness.noCoverage"),
      revisions: t("harness.revisions"),
      blocking: t("harness.blocking"),
      advisory: t("harness.advisory"),
      guides: t("harness.guides"),
      guidesWithoutSensors: t("harness.guidesWithoutSensors"),
      effectivenessTitle: t("harness.effectivenessTitle"),
      noEffectiveness: t("harness.noEffectiveness"),
      capabilitiesTitle: t("harness.capabilitiesTitle"),
      reworkAfterFail: t("harness.reworkAfterFail"),
      reworkAfterPass: t("harness.reworkAfterPass"),
      lift: t("harness.lift"),
      capability: t("harness.capability"),
      withCapability: t("harness.withCapability"),
      withoutCapability: t("harness.withoutCapability"),
      noCapabilities: t("harness.noCapabilities"),
    },
    budget: {
      title: t("budget.title"),
      subtitle: t("budget.subtitle"),
      escalations: t("budget.escalations"),
      terminations: t("budget.terminations"),
      guardrailTrips: t("budget.guardrailTrips"),
      warnNotSurfaced: t("budget.warnNotSurfaced"),
      byKind: t("budget.byKind"),
      unattributedLegacy: t("budget.unattributedLegacy"),
    },
    costBreakdown: {
      byModelTitle: t("costBreakdown.byModelTitle"),
      byRunnerTitle: t("costBreakdown.byRunnerTitle"),
      modelHeader: t("costBreakdown.modelHeader"),
      runnerHeader: t("costBreakdown.runnerHeader"),
      inputHeader: t("costBreakdown.inputHeader"),
      outputHeader: t("costBreakdown.outputHeader"),
      cacheHeader: t("costBreakdown.cacheHeader"),
      totalHeader: t("costBreakdown.totalHeader"),
      empty: t("costBreakdown.empty"),
      byKindTitle: t("costBreakdown.byKindTitle"),
      storedLifetime: t("costBreakdown.storedLifetime"),
    },
    agentization: {
      title: t("agentization.title"),
      subtitle: t("agentization.subtitle"),
      lines: t("agentization.lines"),
      deliveryUnits: t("agentization.deliveryUnits"),
      additions: t("agentization.additions"),
      deletions: t("agentization.deletions"),
      asOf: t("agentization.asOf"),
      insufficient: t("agentization.insufficient"),
      volatility: t("agentization.volatility"),
      flow: t("agentization.flow"),
      scratch: t("agentization.scratch"),
      agent: t("agentization.agent"),
      trend: t("agentization.trend"),
    },
    funnel: {
      title: t("funnel.title"),
      subtitle: t("funnel.subtitle"),
      runKind: t("funnel.runKind"),
      launchMode: t("funnel.launchMode"),
      triggerSource: t("funnel.triggerSource"),
      humanTouch: t("funnel.humanTouch"),
      throughput: t("funnel.throughput"),
      promotionLane: t("funnel.promotionLane"),
      pureAutonomous: t("funnel.pureAutonomous"),
      aiWithCorrection: t("funnel.aiWithCorrection"),
      humanTakeover: t("funnel.humanTakeover"),
      platformPromoted: t("funnel.platformPromoted"),
      failed: t("funnel.failed"),
      crashed: t("funnel.crashed"),
      abandoned: t("funnel.abandoned"),
      unrecorded: t("funnel.unrecorded"),
    },
  };
}
