import type { DeliveryRunKind } from "@/lib/observatory/run-kind";
import type { getTranslations } from "next-intl/server";
import type { ObservatoryLabels } from "@/components/observatory/types";
import type { RunOutcomeBucket } from "@/lib/runs/outcome-bucket";

import { DELIVERY_RUN_KINDS } from "@/lib/observatory/run-kind";
import { RUN_OUTCOME_BUCKETS } from "@/lib/runs/outcome-bucket";

type Translator = Awaited<ReturnType<typeof getTranslations>>;

/**
 * `tBucket` and `tKind` are the TOP-LEVEL `runBucket` / `runKind` namespaces,
 * not `observatory.*` subtrees: the `/runs` ledger renders the same ten bucket
 * names and the same three kind names from the same keys, and a second copy
 * under `observatory.*` is how two surfaces end up disagreeing about what
 * "PR open" or "scratch" is called — which is exactly what happened while the
 * filter bar read `agentization.*` ("Scratch") and the overview table read its
 * own copy ("Черновой").
 */
export function labelsFromTranslations(
  t: Translator,
  tBucket: Translator,
  tKind: Translator,
): ObservatoryLabels {
  return {
    title: t("title"),
    subtitle: t("subtitle"),
    projectTitle: t("projectTitle"),
    correctionRate: t("correctionRate"),
    correctionFormula: t("correctionFormula"),
    rework: t("rework"),
    retries: t("retries"),
    runs: t("runs"),
    autonomyScore: t("autonomyScore"),
    waitTime: t("waitTime"),
    openWaits: t("openWaits"),
    volatile: t("volatile"),
    reviewDwellExcluded: t("reviewDwellExcluded"),
    nodes: t("nodes"),
    noNodes: t("noNodes"),
    artifacts: t("artifacts"),
    noArtifacts: t("noArtifacts"),
    signals: t("signals"),
    noSignals: t("noSignals"),
    observationsOnly: t("observationsOnly"),
    filters: t("filters"),
    artifactDefId: t("artifactDefId"),
    artifactKind: t("artifactKind"),
    flow: t("flow"),
    runKind: t("runKind"),
    flowRuns: t("flowRuns"),
    flowLedgerOnly: t("flowLedgerOnly"),
    node: t("node"),
    all: t("all"),
    drillDown: t("drillDown"),
    latestAttempt: t("latestAttempt"),
    historicalAttempts: t("historicalAttempts"),
    gates: t("gates"),
    hitlWaits: t("hitlWaits"),
    kind: {
      gate: t("kind.gate"),
      retry: t("kind.retry"),
      rework: t("kind.rework"),
    },
    harness: {
      sectionTitle: t("harness.sectionTitle"),
      sectionSubtitle: t("harness.sectionSubtitle"),
      firingTitle: t("harness.firingTitle"),
      noFiring: t("harness.noFiring"),
      gate: t("harness.gate"),
      kind: t("harness.kind"),
      mode: t("harness.mode"),
      executions: t("harness.executions"),
      passed: t("harness.passed"),
      failed: t("harness.failed"),
      stale: t("harness.stale"),
      failRate: t("harness.failRate"),
      neverFired: t("harness.neverFired"),
      neverFiredHint: t("harness.neverFiredHint"),
      insufficientData: t("harness.insufficientData"),
      byKind: t("harness.byKind"),
      coverageTitle: t("harness.coverageTitle"),
      noCoverage: t("harness.noCoverage"),
      revisions: t("harness.revisions"),
      blocking: t("harness.blocking"),
      advisory: t("harness.advisory"),
      guides: t("harness.guides"),
      guidesWithoutSensors: t("harness.guidesWithoutSensors"),
      effectivenessTitle: t("harness.effectivenessTitle"),
      noEffectiveness: t("harness.noEffectiveness"),
      capabilitiesTitle: t("harness.capabilitiesTitle"),
      reworkAfterFail: t("harness.reworkAfterFail"),
      reworkAfterPass: t("harness.reworkAfterPass"),
      lift: t("harness.lift"),
      capability: t("harness.capability"),
      withCapability: t("harness.withCapability"),
      withoutCapability: t("harness.withoutCapability"),
      noCapabilities: t("harness.noCapabilities"),
    },
    budget: {
      title: t("budget.title"),
      subtitle: t("budget.subtitle"),
      escalations: t("budget.escalations"),
      terminations: t("budget.terminations"),
      guardrailTrips: t("budget.guardrailTrips"),
      warnNotSurfaced: t("budget.warnNotSurfaced"),
      byKind: t("budget.byKind"),
      unattributedLegacy: t("budget.unattributedLegacy"),
    },
    costBreakdown: {
      byModelTitle: t("costBreakdown.byModelTitle"),
      byRunnerTitle: t("costBreakdown.byRunnerTitle"),
      modelHeader: t("costBreakdown.modelHeader"),
      runnerHeader: t("costBreakdown.runnerHeader"),
      inputHeader: t("costBreakdown.inputHeader"),
      outputHeader: t("costBreakdown.outputHeader"),
      cacheHeader: t("costBreakdown.cacheHeader"),
      totalHeader: t("costBreakdown.totalHeader"),
      empty: t("costBreakdown.empty"),
      byKindTitle: t("costBreakdown.byKindTitle"),
      byFlowTitle: t("costBreakdown.byFlowTitle"),
      flowHeader: t("costBreakdown.flowHeader"),
    },
    agentization: {
      title: t("agentization.title"),
      subtitle: t("agentization.subtitle"),
      lines: t("agentization.lines"),
      deliveryUnits: t("agentization.deliveryUnits"),
      additions: t("agentization.additions"),
      deletions: t("agentization.deletions"),
      asOf: t("agentization.asOf"),
      insufficient: t("agentization.insufficient"),
      volatility: t("agentization.volatility"),
      trend: t("agentization.trend"),
      trendNoData: t("agentization.trendNoData"),
      trendValue: t("agentization.trendValue"),
      trendAiLines: t("agentization.trendAiLines"),
      trendAllLines: t("agentization.trendAllLines"),
    },
    funnel: {
      title: t("funnel.title"),
      subtitle: t("funnel.subtitle"),
      runKind: t("funnel.runKind"),
      launchMode: t("funnel.launchMode"),
      triggerSource: t("funnel.triggerSource"),
      humanTouch: t("funnel.humanTouch"),
      throughput: t("funnel.throughput"),
      promotionLane: t("funnel.promotionLane"),
      pureAutonomous: t("funnel.pureAutonomous"),
      aiWithCorrection: t("funnel.aiWithCorrection"),
      humanTakeover: t("funnel.humanTakeover"),
      platformPromoted: t("funnel.platformPromoted"),
      failed: t("funnel.failed"),
      crashed: t("funnel.crashed"),
      abandoned: t("funnel.abandoned"),
      unrecorded: t("funnel.unrecorded"),
    },
    views: {
      label: t("views.label"),
      overview: t("views.overview"),
      cost: t("views.cost"),
      quality: t("views.quality"),
      harness: t("views.harness"),
    },
    period: {
      label: t("period.label"),
      preset7: t("period.preset7"),
      preset30: t("period.preset30"),
      preset90: t("period.preset90"),
      from: t("period.from"),
      to: t("period.to"),
      clamped: t("period.clamped"),
      pending: t("period.pending"),
    },
    overview: {
      title: t("overview.title"),
      subtitle: t("overview.subtitle"),
      project: t("overview.project"),
      platform: t("overview.platform"),
      total: t("overview.total"),
      tasks: t("overview.tasks"),
      tasksInWork: t("overview.tasksInWork"),
      tasksStarted: t("overview.tasksStarted"),
      runs: t("overview.runs"),
      inFlight: t("overview.inFlight"),
      settled: t("overview.settled"),
      empty: t("overview.empty"),
      openInLedger: t("overview.openInLedger"),
    },
    quality: {
      projectsTitle: t("quality.projectsTitle"),
      flowsTitle: t("quality.flowsTitle"),
      project: t("quality.project"),
      flow: t("quality.flow"),
      flowRuns: t("quality.flowRuns"),
      wait: t("quality.wait"),
    },
    uncommitted: t("uncommitted"),
    bucket: Object.fromEntries(
      RUN_OUTCOME_BUCKETS.map((bucket) => [bucket, tBucket(bucket)]),
    ) as Record<RunOutcomeBucket, string>,
    runKindName: Object.fromEntries(
      DELIVERY_RUN_KINDS.map((kind) => [kind, tKind(kind)]),
    ) as Record<DeliveryRunKind, string>,
  };
}
