import type { GateKind } from "@/lib/flows/editor/editor-state";
import type { NodeSideFormLabels } from "@/components/flows/node-form/node-side-form";

// A resolved next-intl translator narrowed to the call shape this builder uses
// (string key → string). Both a real `getTranslations` result and the editor's
// `flowEditor` translator are assignable, so the live Flow Studio editor and the
// read-only package-viewer flow detail (M36 T1.4) source identical labels here.
type Translator = (
  key: string,
  values?: Record<string, string | number>,
) => string;

// Builds the full NodeSideForm label bundle from the `flowEditor` next-intl
// namespace — the ONE place these ~60 key paths live (the editor tabs builder
// calls this rather than re-listing them).
export function buildNodeSideFormLabels(te: Translator): NodeSideFormLabels {
  const gateKind: Record<GateKind, string> = {
    command_check: te("toolbar.gateKind.command_check"),
    skill_check: te("toolbar.gateKind.skill_check"),
    ai_judgment: te("toolbar.gateKind.ai_judgment"),
    artifact_required: te("toolbar.gateKind.artifact_required"),
    external_check: te("toolbar.gateKind.external_check"),
    human_review: te("toolbar.gateKind.human_review"),
  };

  return {
    empty: te("nodeForm.empty"),
    action: te("nodeForm.action"),
    settings: te("nodeForm.settings"),
    gates: te("nodeForm.gates"),
    transitions: te("nodeForm.transitions"),
    rework: te("nodeForm.rework"),
    output: te("nodeForm.output"),
    prompt: te("nodeForm.prompt"),
    command: te("nodeForm.command"),
    formSchema: te("nodeForm.formSchema"),
    model: te("nodeForm.model"),
    runner: te("nodeForm.runner"),
    runnerInline: te("nodeForm.runnerInline"),
    session: te("nodeForm.session"),
    sessionDefault: te("nodeForm.sessionDefault"),
    thinkingEffort: te("nodeForm.thinkingEffort"),
    permissionMode: te("nodeForm.permissionMode"),
    workspaceAccess: te("nodeForm.workspaceAccess"),
    skills: te("nodeForm.skills"),
    restrictions: te("nodeForm.restrictions"),
    mcps: te("nodeForm.mcps"),
    delegation: te("nodeForm.delegation"),
    maxFanout: te("nodeForm.maxFanout"),
    maxDepth: te("nodeForm.maxDepth"),
    enforcement: {
      title: te("nodeForm.enforcement.title"),
      mcps: te("nodeForm.enforcement.mcps"),
      tools: te("nodeForm.enforcement.tools"),
      skills: te("nodeForm.enforcement.skills"),
      restrictions: te("nodeForm.enforcement.restrictions"),
      permissionMode: te("nodeForm.enforcement.permissionMode"),
      workspaceAccess: te("nodeForm.enforcement.workspaceAccess"),
      hooks: te("nodeForm.enforcement.hooks"),
    },
    timeoutMs: te("nodeForm.timeoutMs"),
    environmentPolicy: te("nodeForm.environmentPolicy"),
    failureClass: te("nodeForm.failureClass"),
    decisions: te("nodeForm.decisions"),
    criticality: te("nodeForm.criticality"),
    roles: te("nodeForm.roles"),
    assignees: te("nodeForm.assignees"),
    allowTakeover: te("nodeForm.allowTakeover"),
    outputSchema: te("nodeForm.outputSchema"),
    outputRequired: te("nodeForm.outputRequired"),
    schemaRef: {
      placeholder: te("nodeForm.schemaRef.placeholder"),
      emptyHint: te("nodeForm.schemaRef.emptyHint"),
      create: te("nodeForm.schemaRef.create"),
      edit: te("nodeForm.schemaRef.edit"),
      paste: te("nodeForm.schemaRef.paste"),
      title: te("nodeForm.schemaRef.title"),
      json: te("nodeForm.schemaRef.json"),
    },
    presentation: te("nodeForm.presentation"),
    presentationWidth: te("nodeForm.presentationWidth"),
    presentationHeight: te("nodeForm.presentationHeight"),
    presentationColor: te("nodeForm.presentationColor"),
    reworkAllowedTargets: te("nodeForm.reworkAllowedTargets"),
    reworkWorkspacePolicies: te("nodeForm.reworkWorkspacePolicies"),
    reworkMaxLoops: te("nodeForm.reworkMaxLoops"),
    reworkCommentsVar: te("nodeForm.reworkCommentsVar"),
    transitionOutcome: te("nodeForm.transitionOutcome"),
    transitionTarget: te("nodeForm.transitionTarget"),
    addTransition: te("nodeForm.addTransition"),
    removeTransition: te("nodeForm.removeTransition"),
    noTransitions: te("nodeForm.noTransitions"),
    noGates: te("nodeForm.noGates"),
    consensus: {
      participants: te("nodeForm.consensus.participants"),
      participantId: te("nodeForm.consensus.participantId"),
      participantSource: te("nodeForm.consensus.participantSource"),
      addParticipant: te("nodeForm.consensus.addParticipant"),
      removeParticipant: te("nodeForm.consensus.removeParticipant"),
      materialAxes: te("nodeForm.consensus.materialAxes"),
      materialAxesHint: te("nodeForm.consensus.materialAxesHint"),
      synthesizerSource: te("nodeForm.consensus.synthesizerSource"),
      runnersGroup: te("nodeForm.consensus.runnersGroup"),
      agentsGroup: te("nodeForm.consensus.agentsGroup"),
      sourcePlaceholder: te("nodeForm.consensus.sourcePlaceholder"),
      sourceEmptyHint: te("nodeForm.consensus.sourceEmptyHint"),
      asRunner: te("nodeForm.consensus.asRunner"),
      asAgent: te("nodeForm.consensus.asAgent"),
      roundsMode: te("nodeForm.consensus.roundsMode"),
      roundsMax: te("nodeForm.consensus.roundsMax"),
      onNoConsensus: te("nodeForm.consensus.onNoConsensus"),
    },
    decide: {
      title: te("nodeForm.decide.title"),
      source: te("nodeForm.decide.source"),
      sourceNone: te("nodeForm.decide.sourceNone"),
      sourceOutput: te("nodeForm.decide.sourceOutput"),
      sourceVerdict: te("nodeForm.decide.sourceVerdict"),
      path: te("nodeForm.decide.path"),
      when: te("nodeForm.decide.when"),
      target: te("nodeForm.decide.target"),
      default: te("nodeForm.decide.default"),
      addCase: te("nodeForm.decide.addCase"),
      removeCase: te("nodeForm.decide.removeCase"),
      noCases: te("nodeForm.decide.noCases"),
      onMismatch: te("nodeForm.decide.onMismatch"),
      onMismatchNone: te("nodeForm.decide.onMismatchNone"),
      onMismatchRetry: te("nodeForm.decide.onMismatchRetry"),
      hint: te("nodeForm.decide.hint"),
    },
    hooks: {
      title: te("nodeForm.hooks.title"),
      repetitionMax: te("nodeForm.hooks.repetitionMax"),
      noProgressMaxTurns: te("nodeForm.hooks.noProgressMaxTurns"),
      pathGuardAllowedPaths: te("nodeForm.hooks.pathGuardAllowedPaths"),
      disabled: te("nodeForm.hooks.disabled"),
      hint: te("nodeForm.hooks.hint"),
    },
    promptComposer: {
      placeholder: te("nodeForm.promptComposer.placeholder"),
      unsupported: te("nodeForm.promptComposer.unsupported"),
    },
    multiSelect: {
      add: te("nodeForm.multiSelect.add"),
      remove: te("nodeForm.multiSelect.remove"),
      placeholder: te("nodeForm.multiSelect.placeholder"),
      empty: te("nodeForm.multiSelect.empty"),
    },
    stringList: {
      add: te("nodeForm.stringList.add"),
      remove: te("nodeForm.stringList.remove"),
      placeholder: te("nodeForm.stringList.placeholder"),
    },
    gate: {
      mode: te("gate.mode"),
      modeBlocking: te("gate.modeBlocking"),
      modeAdvisory: te("gate.modeAdvisory"),
      command: te("gate.command"),
      prompt: te("gate.prompt"),
      skill: te("gate.skill"),
      confidenceMin: te("gate.confidenceMin"),
      externalDescription: te("gate.externalDescription"),
      staleOnNewCommit: te("gate.staleOnNewCommit"),
      remove: te("gate.remove"),
      kind: gateKind,
    },
  };
}
