packages:
  - web
  - supervisor
  - mcp

dangerouslyAllowAllBuilds: true

minimumReleaseAgeExclude:
  - icu-minify@4.13.0
  - next-intl-swc-plugin-extractor@4.13.0
  - next-intl@4.13.0
  - use-intl@4.13.0
  - '@xyflow/react@12.11.0'
  - '@xyflow/system@0.0.77'
