import "server-only";

/**
 * `GET /sw.js` — the push service worker (ADR-172 D13).
 *
 * A route handler rather than a `public/` file for one reason: the script must
 * be served with `Service-Worker-Allowed: /` so its registered SCOPE is the
 * whole origin. A worker served from `/sw.js` would default to scope `/`
 * anyway, but the header is what keeps that true if the file ever moves, and a
 * static asset cannot carry it.
 *
 * The worker holds no secrets and no user data. It receives an already-built
 * notification payload and shows it; everything that decides WHETHER to notify
 * lives server-side (`NTF-08`).
 */

const SERVICE_WORKER = `// MAIster push service worker (ADR-172). Generated by app/sw.js/route.ts.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) =>
  event.waitUntil(self.clients.claim()),
);

self.addEventListener("push", (event) => {
  if (!event.data) return;

  let payload;

  try {
    payload = event.data.json();
  } catch {
    // A push body that is not the envelope is ignored rather than shown: a
    // notification built from an unparsed blob is worse than none.
    return;
  }

  const title = typeof payload.title === "string" ? payload.title : "MAIster";
  const body = typeof payload.body === "string" ? payload.body : "";
  // Same-origin, path-only. VAPID already restricts who can push here, so this
  // is depth, not the gate — but a click handler that will navigate wherever a
  // payload says is one compromised dependency away from being the gate.
  const url =
    typeof payload.url === "string" &&
    payload.url.startsWith("/") &&
    !payload.url.startsWith("//")
      ? payload.url
      : "/";
  // One tag per notification KIND, so a second digest replaces the first
  // instead of stacking. At-least-once delivery means the same fact can arrive
  // twice, and two identical banners is the shape readers mute.
  const tag = typeof payload.tag === "string" ? payload.tag : "maister";

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      tag,
      renotify: false,
      data: { url },
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const raw = (event.notification.data && event.notification.data.url) || "/";
  const target =
    typeof raw === "string" && raw.startsWith("/") && !raw.startsWith("//")
      ? raw
      : "/";
  const wanted = new URL(target, self.location.origin).href;

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windows) => {
        for (const client of windows) {
          // Compare resolved URLs. An endsWith match was far too loose: a
          // target of "/" matched every window whose url ends in a slash.
          // (No backticks in here — this whole worker is a template literal.)
          if (client.url === wanted && "focus" in client) return client.focus();
        }

        return self.clients.openWindow(target);
      }),
  );
});
`;

export function GET(): Response {
  return new Response(SERVICE_WORKER, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The scope-widening header. Without it a worker served from a nested
      // path could only control that path.
      "Service-Worker-Allowed": "/",
      // A stale worker is worse than an extra request: the browser re-checks
      // the script on every navigation anyway.
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
