import "server-only";

/**
 * `GET /sw.js` — the push service worker (ADR-172 D13).
 *
 * A route handler rather than a `public/` file for one reason: the script must
 * be served with `Service-Worker-Allowed: /` so its registered SCOPE is the
 * whole origin. A worker served from `/sw.js` would default to scope `/`
 * anyway, but the header is what keeps that true if the file ever moves, and a
 * static asset cannot carry it.
 *
 * The worker holds no secrets and no user data. It receives an already-built
 * notification payload and shows it; everything that decides WHETHER to notify
 * lives server-side (`NTF-08`).
 */

const SERVICE_WORKER = `// MAIster push service worker (ADR-172). Generated by app/sw.js/route.ts.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) =>
  event.waitUntil(self.clients.claim()),
);

self.addEventListener("push", (event) => {
  if (!event.data) return;

  let payload;

  try {
    payload = event.data.json();
  } catch {
    // A push body that is not the envelope is ignored rather than shown: a
    // notification built from an unparsed blob is worse than none.
    return;
  }

  const title = typeof payload.title === "string" ? payload.title : "MAIster";
  const body = typeof payload.body === "string" ? payload.body : "";
  const url = typeof payload.url === "string" ? payload.url : "/";
  // One tag per notification KIND, so a second digest replaces the first
  // instead of stacking. At-least-once delivery means the same fact can arrive
  // twice, and two identical banners is the shape readers mute.
  const tag = typeof payload.tag === "string" ? payload.tag : "maister";

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      tag,
      renotify: false,
      data: { url },
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const target =
    (event.notification.data && event.notification.data.url) || "/";

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windows) => {
        for (const client of windows) {
          if (client.url.endsWith(target) && "focus" in client) {
            return client.focus();
          }
        }

        return self.clients.openWindow(target);
      }),
  );
});
`;

export function GET(): Response {
  return new Response(SERVICE_WORKER, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The scope-widening header. Without it a worker served from a nested
      // path could only control that path.
      "Service-Worker-Allowed": "/",
      // A stale worker is worse than an extra request: the browser re-checks
      // the script on every navigation anyway.
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
