export const LIBRARIAN_WEB_PORT = 3103;
export const LIBRARIAN_SUPERVISOR_PORT = 7798;
export const LIBRARIAN_SUPERVISOR_CONTROL_PORT = 7799;
export const LIBRARIAN_WEB_CONTROL_PORT = 3104;
export const LIBRARIAN_SUPERVISOR_URL = `http://127.0.0.1:${LIBRARIAN_SUPERVISOR_PORT}`;
