import "server-only";

import { open, type FileHandle } from "node:fs/promises";
import path from "node:path";

import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import pino from "pino";

import { getDb } from "@/lib/db/client";
import * as schemaModule from "@/lib/db/schema";
import { keepaliveMs } from "@/lib/runs/keepalive-config";

// FIXME(any): dual drizzle-orm peer-dep variants.
const { projects, runs } = schemaModule as unknown as Record<string, any>;

const log = pino({
  name: "api-runs-stream",
  level: process.env.LOG_LEVEL ?? "info",
});

const TERMINAL_RUN_STATUS = new Set(["Done", "Abandoned", "Failed", "Crashed"]);

const POLL_INTERVAL_MS = 100;
const STATUS_REFRESH_MS = 500;
const CHUNK_SIZE = 64 * 1024;

function runtimeRoot(): string {
  return process.env.MAISTER_RUNTIME_ROOT ?? process.cwd();
}

type RouteParams = { params: Promise<{ runId: string }> };

type RunLite = {
  id: string;
  status: string;
  currentStepId: string | null;
  projectId: string;
  projectSlug: string;
};

async function loadRunLite(runId: string): Promise<RunLite | null> {
  const db = getDb() as any;
  const rows = await db
    .select({
      id: runs.id,
      status: runs.status,
      currentStepId: runs.currentStepId,
      projectId: runs.projectId,
      slug: projects.slug,
    })
    .from(runs)
    .innerJoin(projects, eq(projects.id, runs.projectId))
    .where(eq(runs.id, runId));

  const row = rows[0];

  if (!row) return null;

  return {
    id: row.id,
    status: row.status,
    currentStepId: row.currentStepId,
    projectId: row.projectId,
    projectSlug: row.slug,
  };
}

async function refreshRunStatus(
  runId: string,
): Promise<{ status: string; currentStepId: string | null } | null> {
  const db = getDb() as any;
  const rows = await db
    .select({ status: runs.status, currentStepId: runs.currentStepId })
    .from(runs)
    .where(eq(runs.id, runId));
  const row = rows[0];

  if (!row) return null;

  return { status: row.status, currentStepId: row.currentStepId };
}

function eventsLogPath(projectSlug: string, runId: string): string {
  return path.join(
    runtimeRoot(),
    ".maister",
    projectSlug,
    "runs",
    runId,
    "run.events.jsonl",
  );
}

function parseLastEventId(req: NextRequest): number {
  const header = req.headers.get("last-event-id");
  const query = new URL(req.url).searchParams.get("lastEventId");
  const raw = header ?? query;

  if (!raw) return 0;
  const n = Number.parseInt(raw, 10);

  return Number.isFinite(n) && n >= 0 ? n : 0;
}

function delay(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}

async function readAvailable(
  fh: FileHandle,
  offset: number,
): Promise<{ chunk: Uint8Array; nextOffset: number }> {
  const buf = new Uint8Array(CHUNK_SIZE);
  const { bytesRead } = await fh.read(buf, 0, CHUNK_SIZE, offset);

  return {
    chunk: buf.subarray(0, bytesRead),
    nextOffset: offset + bytesRead,
  };
}

// Durable events that DO advance Last-Event-ID. We deliberately do NOT
// emit a custom `event: <type>` field: browser EventSource dispatches
// named events ONLY to `addEventListener(<eventName>)`, never to the
// `onmessage` handler. Keeping every event on the default `message`
// dispatch lets consumers discriminate on the `type` field carried
// inside `data` without having to register a listener per variant.
function formatSseEvent(monotonicId: number, data: string): string {
  return `id: ${monotonicId}\ndata: ${data}\n\n`;
}

// Synthetic events generated by the web bridge itself (NOT appended to
// run.events.jsonl). They must NOT carry an `id:` line — if they did,
// the browser would store that id as Last-Event-ID and skip the next
// real durable event with the same monotonicId after reconnect.
function formatSyntheticSseEvent(data: string): string {
  return `data: ${data}\n\n`;
}

export async function GET(
  req: NextRequest,
  { params }: RouteParams,
): Promise<Response> {
  const { runId } = await params;
  const lastEventId = parseLastEventId(req);
  const run = await loadRunLite(runId);

  if (!run) {
    return NextResponse.json(
      { code: "PRECONDITION", message: `run not found: ${runId}` },
      { status: 404 },
    );
  }

  const startedAt = Date.now();
  let eventsSent = 0;
  let disconnectReason: "client-disconnect" | "terminal" | "timeout" =
    "terminal";

  log.info(
    {
      runId,
      lastEventId,
      currentStepId: run.currentStepId,
      status: run.status,
    },
    "stream connect",
  );

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const encoder = new TextEncoder();
      let cursor = 0;
      let lastSeen = lastEventId;
      let fh: FileHandle | null = null;
      const projectSlug = run.projectSlug;
      const logPath = eventsLogPath(projectSlug, runId);
      let lastStatusCheck = Date.now();
      let consecutiveEmpty = 0;
      const maxQuietMs = keepaliveMs();
      let pending = "";

      const cleanup = async () => {
        if (fh) {
          try {
            await fh.close();
          } catch {
            /* ignore */
          }
          fh = null;
        }
        try {
          controller.close();
        } catch {
          /* ignore double-close */
        }
      };

      req.signal.addEventListener("abort", () => {
        disconnectReason = "client-disconnect";
        log.info(
          {
            runId,
            eventsSent,
            durationMs: Date.now() - startedAt,
            reason: disconnectReason,
          },
          "stream disconnect (client)",
        );
        void cleanup();
      });

      const drainPending = () => {
        let nl = pending.indexOf("\n");

        while (nl !== -1) {
          const line = pending.slice(0, nl);

          pending = pending.slice(nl + 1);
          if (line.trim().length > 0) {
            try {
              const ev = JSON.parse(line) as {
                type: string;
                monotonicId: number;
              };

              if (
                typeof ev.monotonicId === "number" &&
                ev.monotonicId > lastSeen
              ) {
                lastSeen = ev.monotonicId;
                controller.enqueue(
                  encoder.encode(formatSseEvent(ev.monotonicId, line)),
                );
                eventsSent += 1;
              }
            } catch {
              /* skip malformed line */
            }
          }
          nl = pending.indexOf("\n");
        }
      };

      try {
        while (!req.signal.aborted) {
          if (!fh) {
            try {
              fh = await open(logPath, "r");
              cursor = 0;
              pending = "";
            } catch (err) {
              if ((err as NodeJS.ErrnoException).code === "ENOENT") {
                if (Date.now() - startedAt > maxQuietMs) {
                  disconnectReason = "timeout";
                  break;
                }
                await delay(POLL_INTERVAL_MS);
                continue;
              }
              throw err;
            }
          }

          const { chunk, nextOffset } = await readAvailable(fh, cursor);

          cursor = nextOffset;
          if (chunk.length > 0) {
            consecutiveEmpty = 0;
            pending += new TextDecoder().decode(chunk);
            drainPending();
          } else {
            consecutiveEmpty += 1;
          }

          if (Date.now() - lastStatusCheck >= STATUS_REFRESH_MS) {
            lastStatusCheck = Date.now();
            const status = await refreshRunStatus(runId);

            if (!status) break;
            if (TERMINAL_RUN_STATUS.has(status.status)) {
              const { chunk: tail } = await readAvailable(fh, cursor);

              if (tail.length > 0) {
                pending += new TextDecoder().decode(tail);
                drainPending();
              }
              disconnectReason = "terminal";
              break;
            }
          }

          if (consecutiveEmpty * POLL_INTERVAL_MS > maxQuietMs) {
            disconnectReason = "timeout";
            // No `id:` line: this synthetic event is NOT in
            // run.events.jsonl, so it MUST NOT advance the client's
            // Last-Event-ID — otherwise the next durable event with
            // the same monotonicId would be filtered out on reconnect.
            controller.enqueue(
              encoder.encode(
                formatSyntheticSseEvent(
                  JSON.stringify({
                    type: "session.stream_timeout",
                    reason: "no events within keepalive window",
                  }),
                ),
              ),
            );
            break;
          }

          await delay(POLL_INTERVAL_MS);
        }
      } catch (err) {
        log.warn(
          {
            runId,
            err: err instanceof Error ? err.message : String(err),
          },
          "stream loop error",
        );
      } finally {
        await cleanup();
        log.info(
          {
            runId,
            eventsSent,
            durationMs: Date.now() - startedAt,
            reason: disconnectReason,
          },
          "stream disconnect",
        );
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}
